spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gang?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rhdwk9216
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
server:
  port: 8080