spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    include: oauth
server:
  port: 8080